development:
  sessions:
    default:
      database: rails_grape_template_development
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false
test:
  sessions:
    default:
      database: rails_grape_template_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
